### ISSUE TITLE
Camera distortion parameter

### ISSUE THREAD

**Issue by YuShaorong01** [THU-LYJ-Lab/SS3DM-Exporter#9] opened 2024-11-22 09:40 UTC
Thank you for your open source. I found that in the data set, except for the forward and backward cameras, the pictures of other side cameras seem to have distortion. However, the distortion parameters in the camera parameter file are all 0. How can I obtain normal pictures?

**Comment by BlueNine9** [comment] 2024-11-27 06:17
This issue appears to be a duplicate of #8. Please refer to our reply there.

**Closed as completed by BlueNine9** 2024-11-27 06:17 UTC
